### ISSUE TITLE
JS Frameworks Benchmark submission?

### ISSUE THREAD

**Issue by ryansolid** [Marcisbee/radi#52]
Whenever I see library that makes bold performance claims I always like to point them this way. Not only is this benchmark a great comparison, it's a great tuning tool. The more strong performing libraries better the community. Many of the fastest libraries have made submissions the past few months and it really illustrates the tradeoffs of different approaches.

https://github.com/krausest/js-framework-benchmark

**Comment by Marcisbee** [comment]
Thanks @ryansolid !
Will add it when Radi comes out of BETA.
Radi is not production ready jet, API is changing, so I don't really want to publish it there for now.

**Comment by Dan-Do** [comment]
Hello, what is the state now? It seems the projects was abbandoned?

**Comment by Marcisbee** [comment]
The reality is that this project is probably never reaching v1.

I think it served its purpouse - got me learning in public about open source and FE framework internals (game changin experience for me) and boosted other performance chasing framework creation and updates.

I don't want Radi to match some other framework API. Since it started to match React too much I really lost all of the reasons WHY continue with this, because performance alone in not that much of a seller. When hooks came out, the API I was working on for Radi was almost identical to hooks, so I just had less and less reasons to continue.

I'm still figuring out and finding new ways to improve FE framework performance, if some day I come up with something, this project will be where I'll put it.
